### ISSUE TITLE
Dispose a scratch card

### ISSUE THREAD

**Issue by HlodowigRaginwald** [connesc/scratchcard#2]
I need to reset and recreate a scratchcard on the fly but the div of the old scratchcard remains.
There is a method to destroy an instance of a scratchcard whose delete the dom ?

**Comment by connesc** [comment]
I just added this feature to v0.4.0: 67a0079f6fde8184d64d7399725d0d9a86e54788.
You can now detach the scratchcard from the DOM like this:

``` javascript
scratchcard.setElement(null);
```
