### ISSUE TITLE
IE10 requiring double-click

### ISSUE THREAD

**Issue by jordanmaslyn** [connesc/scratchcard#3]
Hey there! Thanks for this awesome resource.

I am having a weird issue where IE10 is requiring a double-click and hold to "scratch". Any thoughts on a fix for this?

**Comment by connesc** [comment]
Hi ! Thanks for this report.

I have no access to Windows for now. I tried a live IE10 session on Sauce Labs, but I was not able to reproduce this behavior. I will try a real Windows ASAP.

Meanwhile:
- What OS are you using?
- Can you reproduce the issue with the [live demo](http://connesc.github.io/scratchcard/example/)?

**Comment by jordanmaslyn** [comment]
Dang, good thinking. I didn't think to try on the live demo. It is working for me on the Live Demo so must be something I am doing on my own setup. Thanks for your help. It's a very helpful tool!

**Comment by connesc** [comment]
OK, no problem! :wink:
Do not hesitate to reopen if you think that `scratchcard` is involved in any way.
