### ISSUE TITLE
 Painter - put image in place of color

### ISSUE THREAD

**Issue by thaiCarvalho** [connesc/scratchcard#5]
Hi! 

There is a way to put an image in place of color? 

Thanks!

**Comment by connesc** [comment]
Hi!

Never did it myself, but `Painter` has been designed to be extended for that kind of case.

You should be able to override the `Painter.reset` method (either by subclassing or monkey patching the default implementation) and use the [`drawImage` API](https://www.w3schools.com/tags/canvas_drawimage.asp) to intialize the scratching surface with your image.
