### ISSUE TITLE
Scratchcard resets on resize.

### ISSUE THREAD

**Issue by Levan777** [connesc/scratchcard#6]
Hi,

The scratchcard top layer where you actually scratch it, resets every time window size is changed.

Is this a feature or bug?

thanks

**Comment by connesc** [comment]
Hi,

This is actually a feature.
However, only the size of the hidden element is monitored, not the size of the whole window. So you should be able to avoid resets by making the element size independent from the window size.
Also note that once the element is revealed, it stops resetting on resize.

**Comment by Levan777** [comment]
thanks a lot!!
